// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiD6axe6cyWTdvVF7pcsmrBg7nkTJnJd0',
    appId: '1:968747475828:web:f6ac22375f39cabaa18221',
    messagingSenderId: '968747475828',
    projectId: 'baassari-dd9e0',
    authDomain: 'baassari-dd9e0.firebaseapp.com',
    storageBucket: 'baassari-dd9e0.appspot.com',
    measurementId: 'G-TR8QRBTLBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rU1iEYiXx4nczmGmMy7RWny1qxh7a7c',
    appId: '1:968747475828:android:152b1a66105f6ebba18221',
    messagingSenderId: '968747475828',
    projectId: 'baassari-dd9e0',
    storageBucket: 'baassari-dd9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZmN0qiQZY4Ey10ISh1YVj83ouKC_AmGU',
    appId: '1:968747475828:ios:121170e573b99035a18221',
    messagingSenderId: '968747475828',
    projectId: 'baassari-dd9e0',
    storageBucket: 'baassari-dd9e0.appspot.com',
    iosBundleId: 'com.example.remoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZmN0qiQZY4Ey10ISh1YVj83ouKC_AmGU',
    appId: '1:968747475828:ios:121170e573b99035a18221',
    messagingSenderId: '968747475828',
    projectId: 'baassari-dd9e0',
    storageBucket: 'baassari-dd9e0.appspot.com',
    iosBundleId: 'com.example.remoteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiD6axe6cyWTdvVF7pcsmrBg7nkTJnJd0',
    appId: '1:968747475828:web:04a8dbf46f09b52da18221',
    messagingSenderId: '968747475828',
    projectId: 'baassari-dd9e0',
    authDomain: 'baassari-dd9e0.firebaseapp.com',
    storageBucket: 'baassari-dd9e0.appspot.com',
    measurementId: 'G-6Z9FL6XL15',
  );
}
